### ISSUE TITLE
Question regarding connecting cluster nodes to leader if autounseal is set to false

### ISSUE THREAD

**Issue by rhinck** [binlab/terraform-aws-vault-ha-raft#58] opened 2021-07-31 20:34 UTC
If the value `autounseal` is set to false, does that require me to SSH into every Vault node that is not the leader and try to link them to the leader node?

**Comment by binlab** [comment] 2021-07-31 21:10
To be honest, this case was not tested well. I did a little testing when I just started developing the module. Theoretically, the first time of initialization it will be possible to enter an `unseal` token via **UI**, but after the node is marked as healthy, **ALB** will not switch traffic to it. So far I can not say for sure whether the **Raft** algorithm from **Vault** provides for the distribution of the `unseal` token to the entire cluster, but most likely not

**Comment by binlab** [comment] 2021-07-31 21:12
If after testing it becomes clear that this is not possible, in addition to **SSH**, you can also get access using public access to the nodes, but this is not very secure since the traffic will **not be encrypted**. It is also possible to use another **Vault** for `unseal`, but this is already a chicken and egg issue. Perhaps it makes sense to use other clouds such as **GCP** or **Azure**

**Comment by binlab** [comment] 2021-07-31 21:13
May I ask why there was such a need to refuse to `unseal` with **AWS KMS**?

**Comment by rhinck** [comment] 2021-08-01 00:12
Thanks for the insight!

The main reason I was asking was that before I put Vault into production use, I wanted to test if I was successfully able to do cluster backup and restores. Using `autounseal = true`, I'm able to do a restore if the backup is from the same cluster. If I run `terraform destroy` and delete the cluster, create a new one, and then try to do a restore from the old cluster's backup file, I am unable to unseal the Vault. The unseal keys from the old cluster don't work.

Using `autounseal = false`, I was able to restore the backup of the old cluster onto the new one and unseal it with the old cluster's sharded keys. I am experiencing intermittent issues where the Vault will randomly seal at times and is reporting that the leader is the only node in the cluster although I have specified 3 nodes in the module.

If I understand correctly,  with `autounseal = true` I would need to have the new cluster point to the old AWS KMS key in order to use the old cluster's backup, right? Here's a comment on a vault issue where I got the info from: https://github.com/hashicorp/vault/issues/6046#issuecomment-675464665

If so, do you know how I could implement using an existing AWS KMS key with the module?

**Comment by binlab** [comment] 2021-08-01 16:48
Thanks for reporting!
> The main reason I was asking was that before I put Vault into production use, I wanted to test if I was successfully able to do cluster backup and restores. Using `autounseal = true`, I'm able to do a restore if the backup is from the same cluster. If I run `terraform destroy` and delete the cluster, create a new one, and then try to do a restore from the old cluster's backup file, I am unable to unseal the Vault. The unseal keys from the old cluster don't work.

After Terraform destroys the **KMS** key (inside the module) will be marked as deleted but can be restored in some period of time (**10 days** by module configuration, maybe need to provide an option to configure this value). So you have a chance to restore data from _snapshots_ or **EBS** _snapshots_

> Using `autounseal = false`, I was able to restore the backup of the old cluster onto the new one and unseal it with the old cluster's sharded keys. I am experiencing intermittent issues where the Vault will randomly seal at times and is reporting that the leader is the only node in the cluster although I have specified 3 nodes in the module.

For a cloud deployment with more than 1 node `autounseal = false` is not so good solution, but you can configure "cluster" with one node and `autounseal = false`, and use this just to unseal another cluster. Looks like not for production but should work. 

> If I understand correctly, with `autounseal = true` I would need to have the new cluster point to the old AWS KMS key in order to use the old cluster's backup, right?

Exactly, and on a new version of Vault it supports even migration, more: https://www.vaultproject.io/docs/concepts/seal#seal-migration and https://support.hashicorp.com/hc/en-us/articles/360002040848-Seal-Migration. But it will require a little manual work. In theory, it can be automated, but this is a rather difficult task and will take a lot of time. But this is quite interesting and I probably will add it to the list of tasks

> If so, do you know how I could implement using an existing AWS KMS key with the module?

I have added some configuration and example by this PR https://github.com/binlab/terraform-aws-vault-ha-raft/pull/62, after a quick test, it looks like everything is working as intended. Please test it from your side

**Comment by rhinck** [comment] 2021-08-02 23:45
I just tested #62, and it was working for me, thanks! It is nice to be able to use **KMS** keys instead of manual `unseal` with the sharded keys. The Vault cluster seems to be having less issues as well.

> So you have a chance to restore data from snapshots or EBS snapshots

I was considering making a **Lambda** script that would run on a certain interval and make **Raft** backups and store them in an encrypted **S3** bucket. In your opinion, what is the best option for backup, **EBS** snapshots or the **Raft** ones? Are there any pros or cons to either approach?

**Comment by rhinck** [comment] 2021-08-02 23:53
<img width="395" alt="Screen Shot 2021-08-02 at 4 43 57 PM" src="https://user-images.githubusercontent.com/37898062/127936816-2296cbe2-6dd8-43e7-a843-52df4c33e9ac.png">

Also, if I understand correctly the `node` volumes are used to install the OS and the `raft` volumes are used by each cluster node to store Vault data?

So if I had snapshots and needed to restore them, then I take the snapshots, create new volumes from them, detach the existing volumes from the **ec2** instances, and attach the volumes created from the snapshots to the **ec2** instances?

**Comment by binlab** [comment] 2021-08-05 07:53
> I just tested #62, and it was working for me, thanks! It is nice to be able to use **KMS** keys instead of manual `unseal` with the sharded keys. The Vault cluster seems to be having less issues as well.

Thanks, nice to hear that!

**Comment by binlab** [comment] 2021-08-05 07:58
> I was considering making a **Lambda** script that would run on a certain interval and make **Raft** backups and store them in an encrypted **S3** bucket. In your opinion, what is the best option for backup, **EBS** snapshots or the **Raft** ones? Are there any pros or cons to either approach?

I started thinking about _automatic snapshots_ on the **S3 bucket** from the very beginning of the development of the module, but the main problem is that for this you need to create a system account and policy, and this, in turn, requires initializing the **Vault**. So far, _there is no mechanism for pre-initializing the system user_ (with rights only to create snapshots). Using snapshots with storage on an **S3 bucket** is more preferable from the point of view of money costs and space-saving, but requires post-configuration (as I described before). _But there are never too many backups_ :slightly_smiling_face:

**Comment by binlab** [comment] 2021-08-05 08:00
> Also, if I understand correctly the `node` volumes are used to install the OS and the `raft` volumes are used by each cluster node to store Vault data?

yes, absolutely. A separate **EBS** is needed to store the state of the cluster and data even with a complete re-creation (in case of updating the version of the **Vault**, for example)

**Comment by binlab** [comment] 2021-08-05 08:03
> So if I had snapshots and needed to restore them, then I take the snapshots, create new volumes from them, detach the existing volumes from the **ec2** instances, and attach the volumes created from the snapshots to the **ec2** instances?

Yes, that's right. This is one of the possible options (but I have not tested it). There are many options for how to recover data (if you have them). For example, you can also launch the instance, add an external **EBS**, go to the instance by **SSH** and copy the data and transfer it to a new cluster. Or you can create a separate cluster with one node, and specify the **EBS** snapshot as a source of recovery, and then take a snapshot with your hands using a **Vault UI** or **CLI**.

**Comment by binlab** [comment] 2021-08-05 08:10
> So if I had snapshots and needed to restore them, then I take the snapshots, create new volumes from them, detach the existing volumes from the **ec2** instances, and attach the volumes created from the snapshots to the **ec2** instances?

btw, this is a good point for creating a separate issue for this enhancement! I can investigation this method and it may be possible to completely automate this process. Since **Terraform** has an option [snapshot_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume#snapshot_id) для `aws_ebs_volume` resource

**Closed as completed** 2021-08-09 07:24 UTC
Labels: enhancement, question
